---
title: "ClustringAnalysis"
author: "Rani Basna"
date: "2024-01-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries 

```{r, echo=FALSE, message=FALSE, results='hide'}
# library("factoextra")

library(NbClust)
library(clValid)

library(tibble)
library(tidyverse)
#
# library(missForest)
library(dplyr)
library(M3C)
library(diceR)

library(stringi)
library(tidymodels)
library(mltools) # for the function one_hot
library(data.table) # for the function "as.data.table"
# library(NumericTransformation)
# library(treeClust)
```

```{r, echo=FALSE, results='hide'}
source("../R_code/Rfunctions.R")
```


# Data preparation Full data

```{r}
library(missRanger)
# load the data
miceObj <- readRDS("miceObj.rds")
dataList <- miceRanger::completeData(miceObj)
imp_data <- dataList[[1]] %>% as_tibble()
# Select the ordinal variables
ordinal_varaibles <- imp_data %>% select(where(is.factor)) %>% names() %>% setdiff(c(Correct_twolevs,twolevs))
ordinal_varaibles
# Convert factor to ordinal variables
imp_data[ordinal_varaibles] <- lapply(imp_data[ordinal_varaibles],function(x) {factor(x,ordered = TRUE)})
imp_data %>% select(all_of(ordinal_varaibles)) %>% lapply(levels)
# Prepare the data
OH_data <- OH_dummy_scale(prepared_data = imp_data %>% select(- asthma))
OH_data
#
```


```{r}
# get percentage os missing values for each variable
miss_perc <- apply(data, 2, function(x) sum(is.na(x))/length(x))
miss_perc
# select varaible that have more than 60% missing values 
var_miss_60 <- names(miss_perc[miss_perc > 0.6])
var_miss_60
```


```{r}
# Remove the variables that have more than 60% missing values as they considered auxiliary variables
data_no_aux <- imp_data  %>% select(-all_of(var_miss_60))
# one hot encode the data without the auxiliary variables
OH_data_no_aux <- OH_dummy_scale(prepared_data = data_no_aux %>% select(- asthma))
# Save OH_data and OH_data_no_aux as csv files
write.csv(OH_data, file = "../Intermediates/SavedObjects/OH_data.csv")
write.csv(OH_data_no_aux, file = "../Intermediates/SavedObjects/OH_data_no_aux.csv")
#
# save(OH_data, file = "OH_data.rda")
# save(OH_data_no_aux, file = "OH_data_no_aux.rda")

```


```{r}
# Data assemble
# read the original data
WSAS_phenotyping_data <- haven::read_spss("../Updated asthma phenotyping files/WSAS_phenotyping_data.sav")
# add the variables Adult_onset_asthma, ID and the cohort variables from the WSAS_phenotyping_data to the imputed data as columns 
imp_full_data <- cbind(imp_data, WSAS_phenotyping_data %>% select(Adult_onset_asthma, ID, cohort))
# read the clustering results
result_OH_IDEC_No_aux_3 <- read.csv("../Intermediates/SavedObjects/result_as_FcIDEC_clusters_3.csv")

# Add the clustering results to the full imputed data. this mean we should add the cluster column in the result_OH_IDEC_No_aux_3 data frame to the imp_full_data. Note that the clustering is done on only asthmatic patients so we need to have NA the raw is for non-asthmatic patient i.e when asthma == "NO" we should have NA
filtered_imp_df <- imp_full_data %>% filter(asthma == "Yes")
filtered_imp_df$cluster_label <- result_OH_IDEC_No_aux_3$cluster 
imp_full_data <- imp_full_data %>% left_join(filtered_imp_df %>% select(ID, cluster_label), by = "ID")
# save the imp_full_data
write.csv(imp_full_data, file = "../Intermediates/SavedObjects/imp_full_data.csv")
# save the imp_full_data as rds file
saveRDS(imp_full_data, file = "../Intermediates/SavedObjects/Imp_Labeld_data_full.rds")
# read the rds imp_full_data
imp_full_data <- readRDS("../Intermediates/SavedObjects/Imp_Labeld_data_full.rds")

```

```{r}
imp_full_data
```

```{r}
diff_features <- setdiff(names(WSAS_phenotyping_data), names(imp_full_data))
any(is.na(imp_full_data %>% filter(asthma=="No") %>% pull(cluster_label)))
```


```{r}
# get the names of the numerical variables
numerical_vars <- data_no_aux %>% select(where(is.numeric)) %>% names()
numerical_vars
# If you want to save the variable names to a file
write.csv(numerical_vars, '../Intermediates/SavedObjects/numerical_vars.csv', row.names = FALSE)
```


## Optimal number 

### Internal 
```{r}
Nb_OH <- NbClust(OH_data, distance = "manhattan", min.nc = 3, max.nc = 8, method = "kmeans")
summary(Nb_OH)
print(Nb_OH)
```

```{r InternalValidation}
# Nb_OH <- NbClust(OH_data, distance = "euclidean", min.nc = 3, max.nc = 8, method = "kmeans")
Nb_OH <- NbClust(OH_data, distance = "manhattan", min.nc = 3, max.nc = 8, method = "kmeans")
Nb_OH_Euclidian <- NbClust(OH_data, distance = "euclidean", min.nc = 3, max.nc = 8, method = "kmeans")
Nb_OH
fviz_nbclust(Nb_OH)
```


```{r InternalValidation}
clmethods <- c("hierarchical","kmeans","pam")
internal_validation_OH <-clValid(as.data.frame(OH_data), clMethods = clmethods, nClust = 3:8, validation = 'internal', maxitems = 2000, method = 'ward')
summary(internal_validation_OH)
```

### M3C
```{r M3C}
# prepare the data in the right format for the M3C library
my_data_OH_m3c <- data.frame(t(OH_data))

# converted_data_m3c_na <- data.frame(t(converted_data_all_na))
# res_km_RCSI_OH <- M3C(my_data_OH_m3c, removeplots = TRUE, iters=40, clusteralg = "km", objective='RCSI', fsize=8, lthick=1, dotsize=1.25)
res_pam_RCSI_OH <- M3C(my_data_OH_m3c, removeplots = TRUE, iters=25, objective='RCSI', fsize=8, lthick=1, dotsize=1.25)
```

```{r}
res_pam_RCSI_OH$scores
res_pam_RCSI_OH$plots[[1]]
res_pam_RCSI_OH$plots[[2]]
res_pam_RCSI_OH$plots[[4]]
```


## Optimal number without auxiliary variables

### Internal 
```{r InternalValidation}
# Nb_OH <- NbClust(OH_data, distance = "euclidean", min.nc = 3, max.nc = 8, method = "kmeans")
Nb_OH_no_aux <- NbClust(OH_data_no_aux, distance = "manhattan", min.nc = 3, max.nc = 8, method = "kmeans")
Nb_OH_no_aux
summary(Nb_OH_no_aux)
fviz_nbclust(Nb_OH_no_aux)
```


```{r InternalValidation}
clmethods <- c("hierarchical","kmeans","pam")
internal_validation_OH_no_aux <-clValid(as.data.frame(OH_data_no_aux), clMethods = clmethods, nClust = 3:8, validation = 'internal', maxitems = 2000, method = 'ward')
summary(internal_validation_OH_no_aux)
```

### M3C
```{r M3C}
# prepare the data in the right format for the M3C library
my_data_OH_m3c_no_aux <- data.frame(t(OH_data_no_aux))

# converted_data_m3c_na <- data.frame(t(converted_data_all_na))
# res_km_RCSI_OH <- M3C(my_data_OH_m3c, removeplots = TRUE, iters=40, clusteralg = "km", objective='RCSI', fsize=8, lthick=1, dotsize=1.25)
res_pam_RCSI_OH_no_aux <- M3C(my_data_OH_m3c_no_aux, removeplots = TRUE, iters=25, objective='RCSI', fsize=8, lthick=1, dotsize=1.25)
```

```{r}
res_pam_RCSI_OH_no_aux$scores
res_pam_RCSI_OH_no_aux$plots[[1]]
res_pam_RCSI_OH_no_aux$plots[[2]]
res_pam_RCSI_OH_no_aux$plots[[4]]
```

# Clustering


### K-means on OH encoded data
```{r}
set.seed(22)
k_OH <- kmeans(OH_data, centers = 3, nstart = 25)
table(k_OH$cluster)
```

### Bootstraped k-means on OH encoded data
```{r}
K_OH <- clusterboot(OH_data, B = 60, bootmethod = "boot", clustermethod = kmeansCBI, krange =4, seed = 22)
grp_k_OH <- K_OH$result$result$cluster
table(grp_k_OH)
```

### DICE

```{r}
# generate a data for tow numerical varaible and one binary variable
SimData <- data.frame(x1 = rnorm(100, 0, 1), x2 = rnorm(100, 0, 1), x3 = sample(c(0,1), 100, replace = TRUE))
SimData
```



```{r dice}
# dice_OH <- dice(OH_data, nk = 2:4, reps = 5, algorithms = c("hc", "km"), cons.funs = c("kmodes"), trim = TRUE, n = 3, evaluate = TRUE)
# library(diceR)
dice_OH <- dice(OH_data, nk = 2:5, reps = 5, algorithms = c("hc", "diana","km","sc","nmf"), cons.funs = c("kmodes", "majority","CSPA","LCE"), trim = TRUE, n = 5, evaluate = TRUE)
dice_OH <- dice(OH_data, nk = 2:5, reps = 5, algorithms = c("hc", "diana","km","sc"), cons.funs = c("kmodes", "majority"), trim = TRUE, n = 5, evaluate = TRUE)
# the optimal number is (we got 3)
dice_OH$indices$k
dice_con <- dice(converted_data_all, nk = 2:6, reps = 5, algorithms = c("sc", "diana","km","hc","nmf"), cons.funs = c("kmodes", "majority"), trim = TRUE, n = 4, evaluate = TRUE)
# the optimal number is
dice_con$indices$k 
#. 2 we will ignore
```


# Data preparation only asthamtic data

```{r}
# load the data
miceObj <- readRDS("miceObj.rds")
dataList <- miceRanger::completeData(miceObj)
imp_data <- dataList[[1]] %>% as_tibble()
# Select the ordinal variables
ordinal_varaibles <- imp_data %>% select(where(is.factor)) %>% names() %>% setdiff(c(Correct_twolevs,twolevs))
ordinal_varaibles
# Convert factor to ordinal variables
imp_data[ordinal_varaibles] <- lapply(imp_data[ordinal_varaibles],function(x) {factor(x,ordered = TRUE)})
imp_data %>% select(all_of(ordinal_varaibles)) %>% lapply(levels)
```


```{r}
# select asthmatic persons
asthmatic_data <- imp_data %>% filter(asthma == 'Yes')
# Prepare the data
OH_data_as <- OH_dummy_scale(prepared_data = asthmatic_data %>% select(- asthma))
OH_data_as
#
```


```{r}
# get percentage os missing values for each variable
miss_perc <- apply(data, 2, function(x) sum(is.na(x))/length(x))
miss_perc
# select varaible that have more than 60% missing values 
var_miss_60 <- names(miss_perc[miss_perc > 0.6])
var_miss_60
```


```{r}
# Remove the variables that have more than 60% missing values as they considered auxiliary variables
data_no_aux <- imp_data  %>% select(-all_of(var_miss_60))
# select asthmatic persons
asthmatic_data <- data_no_aux %>% filter(asthma == 'Yes')
# one hot encode the data without the auxiliary variables
OH_data_no_aux <- OH_dummy_scale(prepared_data = asthmatic_data %>% select(- asthma))

# Save OH_data and OH_data_no_aux as csv files
write.csv(OH_data, file = "../Intermediates/SavedObjects/OH_data.csv")
write.csv(OH_data_no_aux, file = "../Intermediates/SavedObjects/OH_data_no_aux_as.csv")
#
# save(OH_data, file = "OH_data.rda")
# save(OH_data_no_aux, file = "OH_data_no_aux.rda")

```


```{r}
# get the names of the numerical variables
numerical_vars <- data_no_aux %>% select(where(is.numeric)) %>% names()
numerical_vars
# If you want to save the variable names to a file
write.csv(numerical_vars, '../Intermediates/SavedObjects/numerical_vars.csv', row.names = FALSE)
```


## Optimal number 

### Internal 
```{r}
Nb_OH_as <- NbClust(OH_data_no_aux, distance = "manhattan", min.nc = 3, max.nc = 8, method = "kmeans")
Nb_OH_as
```


```{r InternalValidation}
# Nb_OH <- NbClust(OH_data, distance = "euclidean", min.nc = 3, max.nc = 8, method = "kmeans")
Nb_OH_Euclidian_as <- NbClust(OH_data_no_aux, distance = "euclidean", min.nc = 3, max.nc = 8, method = "kmeans")
Nb_OH_Euclidian_as
```

```{r InternalValidation}
clmethods <- c("hierarchical","kmeans","pam")
internal_validation_OH_as <-clValid(as.data.frame(OH_data_no_aux), clMethods = clmethods, nClust = 3:8, validation = 'internal', maxitems = 2000, method = 'ward')
summary(internal_validation_OH_as)
```

### M3C
```{r M3C}
# prepare the data in the right format for the M3C library
my_data_OH_m3c_no_aux <- data.frame(t(OH_data_no_aux))

# converted_data_m3c_na <- data.frame(t(converted_data_all_na))
# res_km_RCSI_OH <- M3C(my_data_OH_m3c, removeplots = TRUE, iters=40, clusteralg = "km", objective='RCSI', fsize=8, lthick=1, dotsize=1.25)
res_pam_RCSI_OH_no_aux <- M3C(my_data_OH_m3c_no_aux, removeplots = TRUE, iters=35, objective='RCSI', fsize=8, lthick=1, dotsize=1.25)
```
```{r}
res_pam_RCSI_OH_no_aux$scores
res_pam_RCSI_OH_no_aux$plots[[1]]
res_pam_RCSI_OH_no_aux$plots[[2]]
res_pam_RCSI_OH_no_aux$plots[[4]]
```
