---
title: "ClusteringResults_temp"
output: html_document
date: '2022-04-26'
# output:
#   html_document:
#     theme: united
#     highlight: tango
#     toc: yes
#     toc_depth: 3
#     toc_float: yes
#     number_sections: yes
---

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- ``` -->


```{r, echo=FALSE, results='hide'}
# source("../../R_code/Rfunctions.R")
# source("/Users/ra1077ba/Documents/DataScience/GU/AsthmaClusteringMuwada/R_code/Rfunctions.R")
```


```{r, include=FALSE}
library(dplyr)
# library(ggthemes)
library(tidyverse)
library(ggplot2)
library(FactoMineR)
# install.packages("factoextra")
library(factoextra)
# install.packages("arsenal")
library(arsenal)
# library(plotly)
library(cowplot)
# install.packages("treeClust")
library(treeClust)
# install.packages("advclust")
# library(advclust)
#
# install.packages("fmsb")
library(fmsb)
library(colormap)
# install.packages("mltools")
library(mltools)
library(data.table)
library(scales)
#
library(reshape2)
#
# install.packages("GGally")
library(GGally)
library(RColorBrewer)
# install.packages("ggthemes")
library(ggthemes)
# install.packages("hrbrthemes")
library(hrbrthemes)
library(whisker)
```



<!-- ```{r} -->
<!-- section_numbering <- seq(1,4) -->
<!-- section_numbering <- "One" -->
<!-- #whisker::whisker.render("this is the {{section_numbering}}") -->
<!-- ``` -->


<!-- ## Clustering report {{section_numbering}} {.tabset} -->

### Summary table

```{r, results='asis'}
# results_Kam <- get_ClusterResults(OriginalData = my_imp_data, Labels = kamRes$finalMemb)
table_result <- tableby(clusters ~ ., data = as.list(results_cluster_data))
summary(table_result, title = "Charachtaristcs of Clusters")  
```

### Charachtiristic Analysis 

```{r, warning=FALSE, message=FALSE}
catdes(results_cluster_data, dim(results_cluster_data)[2])
```

### Radar Plots

```{r, warning=FALSE, message=FALSE, results='hide'}
radar_plot(labeled_original_data = results_cluster_data, clusters = results_cluster_data$clusters)
```

### parallel box plots

```{r, message=FALSE, echo=FALSE, warning=FALSE, fig.width = 14}
KM_OH_box_plot <- parallel_box_plot(labeled_original_data = results_cluster_data %>% select(- pd20))
KM_OH_box_plot
```

### parallel coordinate plot

```{r, message=FALSE, echo=FALSE, warning=FALSE, fig.width=14}
# results_cluster_data %>% select(FEV1_FVC_ratio_post, Neutrophiles, Kco, onset_age_asthma)
Par_cor_plot(labeled_original_data = results_cluster_data, selected_vars = c("FEV1_FVC_ratio_post", "Neutrophiles", "kco", "onset_age_asthma"), IsScaled = TRUE)
# Par_cor_plot(labeled_original_data = results_cluster_data, selected_vars = c("exact_age", "bmi2"), IsScaled = TRUE)
```

